#!/bin/bash
# Setup
# Execute as SUDO

RED='\033[0;31m'
GREEN='\033[0;32m'
BINDIR=('Dependencies' 'Scripts')
LIBDIR=('Commands' 'Wordlists')

errCheck(){
    if $? != 0; then
        echo -e "${RED}Error occurred, couldn't copy to $i"
    else echo -e "${GREEN}Copied $i successfully!"
    fi
}

mkdir /usr/local/bin/Info-Scanners /usr/local/lib/Info-Scanners

for i in "${BINDIR[@]}"; do
    cp -r $i /usr/local/bin/Info-Scanners
    $errCheck
done

for i in "${LIBDIR[@]}"; do
    cp -r $i /usr/local/lib/Info-Scanners
    $errCheck
done

echo -e "${GREEN}***  SETUP FINISHED  ***"
echo -e "${GREEN}*** RESTART TERMINAL ***"

exit 0