#!/bin/bash
# DNSScan - Ahaupt3

source /usr/local/lib/Info-Scanners/Misc/globalvar.txt

DIR="$1/Scans/DNS" # FIX THIS, $1 = domain not IP
SCANTYPE='DNS'

usage(){
	echo -e "${RED}Usage: $0 <TARGET-IP>"
	exit 1
}

errCheck(){
    if $? != 0; then
        echo -e "${RED}Error occurred, moving on..."
    else echo -e "${GREEN}Saved to $FILENAME"
    fi
}

if [[ $EUID -ne 0 ]]; then
   echo -e "${RED}This script must be run as root!" 
   exit 1
fi

if (( "$#" != 1 )); then
	usage
fi

if [[ $1 =~ (?=^.{5,254}$)(^(?:(?!\d+\.)[a-zA-Z0-9_\-]{1,63}\.?)+(?:[a-zA-Z]{2,})$) ]]; then
	:
else
	echo -e "${RED}"
	echo -e "${RED}Invalid Domain!"
	echo -e "${RED}"
	usage
fi

if [[ ! -d $DIR ]]; then
    mkdir $DIR
fi

cd $1/Scans/DNS # FIX THIS, $1 = domain not IP

while IFS= read -r CMD
do
	echo -e "${RED}Running $(echo "$CMD" | awk '{print $1;}')..."
	FILENAME="$(echo "$CMD" | awk '{print $1;}').txt"
	$CMD >> $FILENAME
	$errCheck
done < $HOMEDIR/Commands/$SCANTYPE.txt

echo -e "${RED}Checking for Vulnerabilities..."
FILENAME='vulns.txt'
nmap --script vuln -p445 $1 >> $FILENAME
$errCheck
echo "*******************************\n" >> $FILENAME

echo -e "${GREEN}*** ALL SCANS COMPLETE ***"

exit 0