#!/bin/bash
# EmailScan - Ahaupt3

source /usr/local/lib/Info-Scanners/Misc/globalvar.txt

DIR="$1/Scans/Email" # FIX THIS, $1 = domain not IP
SCANTYPE='Email'

usage(){
	echo -e "${RED}Usage: $0 <domain>"
	exit 1
}

errCheck(){
    if $? != 0; then
        echo -e "${RED}Error occurred, moving on..."
    else echo -e "${GREEN}Saved to $FILENAME"
    fi
}

if [[ $EUID -ne 0 ]]; then
   echo -e "${RED}This script must be run as root!" 
   exit 1
fi

if (( "$#" != 1 )); then
	usage
fi

if [[ $1 =~ (?=^.{5,254}$)(^(?:(?!\d+\.)[a-zA-Z0-9_\-]{1,63}\.?)+(?:[a-zA-Z]{2,})$) ]]; then
	:
else
	
	echo -e "${RED}Invalid Domain!"
	
	usage
fi

if [[ ! -d $DIR ]]; then
    mkdir $DIR
fi

cd $1/Scans/Email # FIX THIS, $1 = domain not IP

# Optimize in future by using a loop to iterate cmds & save files
echo -e "${RED}Running theharvester..."
FILENAME='theharvester.txt'
theharvester -d $1 -b google >> $FILENAME
$errCheck

echo -e "${GREEN}*** ALL SCANS COMPLETE ***"

exit 0