#!/bin/bash
# HTTPScan - Ahaupt3

source /usr/local/lib/Info-Scanners/Misc/globalvar.txt

DIR="$1/Scans/HTTP"
SCANTYPE='HTTP'

usage(){
	echo -e "${RED}Usage: $0 <TARGET-IP>"
	exit 1
}

errCheck(){
    if $? != 0; then
        echo -e "${RED}Error occurred, moving on..."
    else echo -e "${GREEN}Saved to $FILENAME"
    fi
}

if [[ $EUID -ne 0 ]]; then
   echo -e "${RED}This script must be run as root!" 
   exit 1
fi

if (( "$#" != 1 )); then
	usage
fi

if [[ $1 =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
	:
else
	
	echo -e "${RED}Invalid IP!"
	
	usage
fi

if [[ ! -d $DIR ]]; then
    mkdir $DIR
fi

cd $1/Scans/HTTP

while IFS= read -r CMD
do
	echo -e "${RED}Running $(echo "$CMD" | awk '{print $1;}')..."
	FILENAME="$(echo "$CMD" | awk '{print $1;}').txt"
	sudo $CMD >> $FILENAME
	$errCheck
done < $HOMEDIR/Commands/$SCANTYPE.txt

echo -e "${RED}Checking for Vulnerabilities..."
FILENAME='vulns.txt'
$errCheck
echo "*******************************\n" >> $FILENAME

echo -e "${GREEN}*** ALL SCANS COMPLETE ***"

exit 0