#!/bin/bash
# HTTPScan - Al3x

RED='\033[0;31m'
YELLOW='\033[0;33m'
GREEN='\033[0;32m'
IP=$1
DIR="${IP}/Scans/HTTP"
SCANTYPE='HTTP'

usage(){
	echo -e "${RED}Usage: $0 <TARGET-IP>"
	exit 1
}

errCheck(){
    if $? != 0; then
        echo -e "${RED}Error occurred, moving on..."
    else echo -e "${GREEN}Saved to $FILENAME"
    fi
}

if (( "$#" != 1 )); then
	usage
fi

if [[ $1 =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
	:
else
	echo -e "${RED}"
	echo -e "${RED}Invalid IP!"
	echo -e "${RED}"
	usage
fi

if [[ ! -d $DIR ]]; then
    mkdir $DIR
fi

cd $IP/Scans/HTTP

while IFS= read -r CMD
do
	echo -e "${RED}Running $(echo "$CMD" | awk '{print $1;}')..."
	FILENAME="$(echo "$CMD" | awk '{print $1;}').txt"
	$CMD >> $FILENAME
	$errCheck
done < ../../Commands/$SCANTYPE.txt

echo -e "${RED}Checking for Vulnerabilities..."
FILENAME='vulns.txt'
$errCheck
echo "*******************************\n" >> $FILENAME

echo -e "${GREEN}*** ALL SCANS COMPLETE ***"

exit 0