#!/bin/bash
# InfoScan - Ahaupt3

source /usr/local/lib/Info-Scanners/Misc/globalvar.txt

DIRS=('Exploits' 'Findings' 'Misc' 'Notes' 'Scans')

usage(){
	echo -e "${RED}Usage: $0 <TARGET-IP>"
	exit 1
}

if [[ $EUID -ne 0 ]]; then
   echo -e "${RED}This script must be run as root!" 
   exit 1
fi

if (( "$#" != 1 )); then
	usage
fi

if [[ $1 =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
	:
else
	echo -e "${RED}"
	echo -e "${RED}Invalid IP!"
	echo -e "${RED}"
	usage
fi

echo -e "${GREEN}*** STARTING SCANS ***"

if [[ ! -d $1 ]]; then
    mkdir $1
fi

for DIR in ${DIRS[@]}; do
    if [[ ! -d $1/$DIR ]]; then
        mkdir $1/$DIR
    fi
done

if [[ ! -d $1/Scans/nmapAutomator ]]; then
    mkdir $1/Scans/nmapAutomator
fi
cd $1/Scans/nmapAutomator
nmapAutomator $1 All

chown -R $SUDO_USER ../../../$1

echo -e "${GREEN}*** ALL SCANS COMPLETE ***

exit 0