#!/bin/bash
# InfoScan - Al3x

while IFS= read -r VAR
do
	VAR
done < $HOMEDIR/Misc/globalvar.text

DIRS=('Exploits' 'Findings' 'Scans')

usage(){
	echo -e "${RED}Usage: $0 <TARGET-IP>"
	exit 1
}

errCheck(){
    if $? != 0; then
        echo -e "${RED}Error occurred, moving on..."
    else echo -e "${GREEN}$0 Scan Successful!"
    fi
}

if (( "$#" != 1 )); then
	usage
fi

if [[ $1 =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
	:
else
	echo -e "${RED}"
	echo -e "${RED}Invalid IP!"
	echo -e "${RED}"
	usage
fi

if [[ ! -d $1 ]]; then
    mkdir $1
fi

for d in ${DIRS[@]}; do
    if [[ ! -d $d ]]; then
        mkdir $1/$d
    fi
done

mkdir $1/Scans/nmapAutomator
cd $1/Scans/nmapAutomator
nmapAutomator $1 All
$errCheck

# nmap -sV -sT -sC $1 -o nmap.txt

echo -e '*** ALL SCANS COMPLETE ***'

exit 0