#!/bin/bash
# LinScan - Al3x

while IFS= read -r VAR
do
	echo $VAR
done < /usr/local/lib/Info-Scanners/Misc/globalvar.txt

DIR="${IP}/Scans/Linux"

usage(){
	echo -e "${RED}Usage: $0 <TARGET-IP>"
	exit 1
}

errCheck(){
    if $? != 0; then
        echo -e "${RED}Error occurred, moving on..."
    else echo -e "${GREEN}Saved to $FILENAME"
    fi
}

if (( "$#" != 1 )); then
	usage
fi

if [[ $1 =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
	:
else
	echo -e "${RED}"
	echo -e "${RED}Invalid IP!"
	echo -e "${RED}"
	usage
fi

if [[ ! -d $DIR ]]; then
    mkdir $DIR
fi

cd $1/Scans/Linux

# Optimize in future by using a loop to iterate cmds & save files

echo -e "${GREEN}*** ALL SCANS COMPLETE ***"

exit 0