#!/bin/bash
# SMBScan - Al3x

RED='\033[0;31m'
YELLOW='\033[0;33m'
GREEN='\033[0;32m'

usage(){
	echo -e "${RED}Usage: $0 <TARGET-IP>"

	exit 1
}

IP=$1

mkdir $IP/Scans/SMB
cd $IP/Scans/SMB

errCheck(){
    if $? != 0; then
        echo -e "${RED}Error occurred, moving on..."
    else echo -e "${GREEN}Saved to $FILENAME"
    fi
}

echo -e "${RED}Running nbtscan..."
FILENAME=nbtscan.txt
nbtscan -r $IP/24 >> $FILENAME
errCheck

echo -e "${RED}Running nmblookup..."
FILENAME=nmblookup.txt
nmblookup -A $IP >> $FILENAME
errCheck

echo -e "${RED}Running enum4linux..."
FILENAME=enum4linux.txt
enum4linux -a $IP >> $FILENAME
enum4linux -o $IP >> $FILENAME
errCheck

echo -e "${RED}Running smbmap..."
FILENAME=smbmap.txt
smbmap -H $IP >> $FILENAME
errCheck

echo -e "${RED}Running smbclient..."
FILENAME=smbclient.txt
smbclient -L $IP >> $FILENAME
errCheck

echo -e "${RED}Running rpcclient enumdomusers..."
FILENAME=rpcclient.txt
bash -c "echo 'enumdomusers' | rpcclient -U '' -N $IP" >> $FILENAME
errCheck

echo -e "${RED}Running nmap..."
FILENAME=nmap.txt
nmap --script smb-enum-shares -p 139,445 $IP >> $FILENAME
errCheck

echo -e "${RED}Checking for Vulnerabilities..."
FILENAME=vulns.txt
nmap --script smb-vuln* -p 139,445 $IP >> $FILENAME
echo "*******************************\n" >> $FILENAME
errCheck

echo -e "${GREEN}*** ALL SCANS COMPLETE ***"

exit 0