#!/bin/bash
# WinScan - Ahaupt3

source /usr/local/lib/Info-Scanners/Misc/globalvar.txt

DIR="${IP}/Scans/Windows"
SCANTYPE='Win'

usage(){
	echo -e "${RED}Usage: $0 <TARGET-IP>"
	exit 1
}

errCheck(){
    if $? != 0; then
        echo -e "${RED}Error occurred, moving on..."
    else echo -e "${GREEN}Saved to $FILENAME"
    fi
}

if [[ $EUID -ne 0 ]]; then
   echo -e "${RED}This script must be run as root!" 
   exit 1
fi

if (( "$#" != 1 )); then
	usage
fi

if [[ $1 =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
	:
else
	
	echo -e "${RED}Invalid IP!"
	
	usage
fi

if [[ ! -d $DIR ]]; then
    mkdir $DIR
fi

cd $1/Scans/Windows

# Optimize in future by using a loop to iterate cmds & save files

echo -e "${GREEN}*** ALL SCANS COMPLETE ***"

exit 0